services:

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z 
    container_name: minio
    environment:
      - MINIO_ROOT_USER=capitol
      - MINIO_ROOT_PASSWORD=C4p1t0lAi2025@
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolutionapi.rule=Host(`minio.capitolia.cloud`)"
      - "traefik.http.services.evolutionapi.loadbalancer.server.port=8080"
      - "traefik.http.routers.evolutionapi.entrypoints=websecure"
      - "traefik.http.routers.evolutionapi.tls.certresolver=mytlschallenge"

    command: server /data --console-address ":9001"
